export const ANONYMOUS_VOTER = 'ANONYMOUS_VOTER';

export const POLL_PHASES = {
  ENTER_POLL: 'ENTER_POLL',
  ERROR_HAPPENED: 'ERROR:HAPPENED',
  SUBMIT_POLL: 'SUBMIT_POLL',
};

export const VOTING_PHASES = {
  CHOSE_VOTE: 'CHOSE_VOTE',
  ERROR_HAPPEND: 'ERROR_HAPPENED',
  SUBMIT_VOTE: 'SUBMIT_VOTE',
  VOTE_SUBMITTED: 'VOTE_SUBMITTED',
};
