export const VOTING_PHASES = {
  CHOSE_VOTE: 'CHOSE_VOTE',
  SUBMIT_VOTE: 'SUBMIT_VOTE',
  VOTE_SUBMITTED: 'VOTE_SUBMITTED',
};

export const POLL_PHASES = {
  ENTER_POLL: 'ENTER_POLL',
  SUBMIT_POLL: 'SUBMIT_POLL',
};
